SENTENCES = [
    "With great power comes great responsibility, said the wise old mentor.",
    "The caped crusader soared above Gotham City under the pale moonlight.",
    "Faster than a speeding bullet, the hero raced to save the day.",
    "A billionaire by day, a vigilante by night, he protected his city.",
    "The team of mutants trained hard to master their incredible abilities.",
    "Wearing his iconic red cape, the hero flew straight into danger.",
    "Armed with a shield and unstoppable courage, the soldier charged forward.",
    "The villain's secret lair was hidden deep beneath the crumbling city.",
    "Her lasso of truth forced even the toughest villains to confess.",
    "Behind the mask, nobody suspected he was the world's greatest hero.",
    "The god of thunder swung his mighty hammer across the stormy sky.",
    "A radioactive spider bite gave him the strength of ten men.",
    "The scarlet speedster ran circles around time itself to save his friends.",
    "Deep in his cave, the detective studied clues late into the night.",
    "Her emerald ring could conjure any object her imagination could create.",
    "The iron suit whirred to life as thrusters ignited beneath his boots.",
    "A green rage monster smashed through walls whenever he lost his temper.",
    "The archer never missed his target, even in the darkest storm.",
    "Underwater, the king of Atlantis commanded armies of loyal sea creatures.",
    "The telepath could hear every thought within a hundred mile radius.",
    "A mysterious symbol appeared in the sky whenever danger threatened the city.",
    "The android learned what it meant to be human through quiet sacrifice.",
    "Her wings shimmered gold as she carried fallen warriors to safety.",
    "The masked vigilante patrolled rooftops long after the city fell asleep.",
    "A young hero discovered his powers on the night of a meteor shower.",
    "The professor gathered gifted students to train them for an uncertain future.",
    "Lightning crackled around her fists as she prepared to face her enemy.",
    "The stealthy assassin moved silently through shadows to protect the innocent.",
    "A powerful amulet granted its wearer the ability to control fire.",
    "The team assembled quickly whenever the world faced its greatest threats.",
    "His metal claws extended with a sound that echoed through the forest.",
    "The sorcerer opened a portal to another dimension with a flick of his wrist.",
    "She could shrink to the size of an ant or grow as tall as a building.",
    "The rogue agent balanced loyalty and duty in a world full of secrets.",
    "A crystal heart powered the ancient suit of armor for a thousand years.",
    "The night sky lit up as fireworks celebrated the city's newest protector.",
    "His invisible jet carried him silently across enemy lines under moonlight.",
    "The scientist's experiment gone wrong turned him into an unstoppable force.",
    "A young orphan trained for years to master the ancient martial arts.",
    "The guardian of the galaxy protected distant worlds from cosmic threats.",
    "Her healing touch could mend wounds that no doctor could ever fix.",
    "The rebel alliance fought bravely against an empire built on fear.",
    "A hidden laboratory held secrets that could change the fate of humanity.",
    "The shapeshifter walked among ordinary people without anyone noticing the difference.",
    "His enhanced senses could detect danger from miles away in total darkness.",
    "The ancient prophecy spoke of a chosen one destined to save the world.",
    "She wielded twin blades forged from a fallen star's molten core.",
    "The rookie hero stumbled through his first battle but never gave up.",
    "A secret organization worked tirelessly to keep the world safe from harm.",
    "The final battle would decide the fate of every living soul on Earth.",
]
